# Password Generator
    # Function Supply ASCII Decimal
        function Get-RandomChar {
        $getRandom = Get-Random -Minimum 33 -Maximum 126

        return [char]$getRandom
        }
    # Function Generate Password
        function Get-RandomConc {
        $passed1 = "$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)"
        $passed2 = "$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)"
        $passed3 = "$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)"
        $passed4 = "$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)"
        $passed5 = "$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)"
        $passed6 = "$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)"
        $passed7 = "$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)"
        $passed8 = "$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)"
        $passed9 = "$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)"
        $passed10 = "$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)$(Get-RandomChar)"
    
        $passed = "$passed1$passed2$passed3$passed4$passed5$passed6$passed7$passed8$passed9$passed10"

        return $passed
        }

Get-RandomConc | ConvertTo-SecureString -AsPlainText -Force | ConvertFrom-SecureString | Set-Content .\Random.txt
